# Use postgres/example user/password credentials

services:

  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: reconhecimento
      POSTGRES_USER: agentereconhecimento
      POSTGRES_PASSWORD: agentereconhecimento
    ports:
      - "5432:5432"
    volumes:
      - reconhecimento:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/reconhecimento
      - DATABASE_USERNAME=agentereconhecimento
      - DATABASE_PASSWORD=agentereconhecimento
    depends_on:
      - db

volumes:
  reconhecimento: