spring.application.name=agente-reconhecimento

spring.h2.console.settings.web-allow-others=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:reconhecimento
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true

security.jwt.public-key=classpath:/rsa/public.pem
security.jwt.private-key=classpath:/rsa/private.key