spring.application.name=agente-reconhecimento

spring.datasource.url=jdbc:postgresql://localhost:5432/agentereconhecimento
spring.datasource.username=agentereconhecimento
spring.datasource.password=agentereconhecimento

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect